### ISSUE TITLE
Decoding issue with asn1ate generated module

### ISSUE THREAD

**Issue by sagarchalise** [kimgr/asn1ate#11]
I am trying to decode the CDR and using asn1ate to generate the pyasn module. I get the error when I try to use the default generated module.

ASN: http://jayu.googlecode.com/svn/!svn/bc/3/trunk/jayu/src/test/testdata/Huawie.txt
Data: http://jayu.googlecode.com/svn/!svn/bc/3/trunk/jayu/src/test/testdata/hua.dat

Generated Code: https://www.dropbox.com/s/hc1b5xocwxecac9/huawei.py?dl=0

If I change all the ```explicitTag``` arguments to ```implicitTag``` argument in the generated code it works. 

Working code after change: https://www.dropbox.com/s/vw477nsdtysmsnc/huawei_change.py?dl=0

Other Samples: http://jayu.googlecode.com/svn/!svn/bc/3/trunk/jayu/src/test/testdata/

**Comment by kimgr** [comment]
This should be fixed as of fa2f75d7480df6a7bb4d5a40661c9721a89b57c9
