### ISSUE TITLE
Automatic tagging not implemented

### ISSUE THREAD

**Issue by james-ward** [kimgr/asn1ate#20]
I'm trying to parse the DSRC definition included in the testdata/public folder.
It uses automatic tagging, which the parser recognises but doesn't act upon. (See line 314 in sema.py)

I'm happy to have a go at implementing this myself and creating a patch, but honestly I don't know what the best way to tackle it would be. Have you any suggestions about where and how to go about adding this?

**Comment by kimgr** [comment]
Hi James, thanks for the report!

I don't quite understand the semantics of automatic tagging, it feels like an ASN.1 definition with it enabled would be pretty useless if the auto-generated tags weren't stable. So I guess ideally you'd want to generate the same tag for the same element, irrespective of order.

But I don't know what other generators do... Can you compare output of some ASN.1->C generators with automatic tags, and see what kind of semantics they have? E.g. this one, which seems competent: https://lionet.info/asn1c/download.html

It feels like this should be a property of the code generator, but it would be nice to put it into the semantic model as well, so different code generators wouldn't have to invent their own mechanisms... Given that the resolution of implicity currently happens in codegen, maybe that's a good place to start, though.

Sorry I don't have more direct advice, but I'm embarrassingly unfamiliar with semantics for ASN.1 feature I haven't used (and likewise with some of the stuff I *have* used :-)).

**Comment by james-ward** [comment]
Latest commit on separate branch now deals with this inside Sema.py. Much nicer solution - thank you for the help.

**Comment by kimgr** [comment]
Thanks, this looks nice! See inline for questions and a few ideas.

**Comment by kimgr** [comment]
Sorry, I didn't see that you had updated this. I'll try and look through it during next week.

**Comment by kimgr** [comment]
This looks great! I have a few ideas for cleanups, but I can do those separately.

It's impressive how small the patch turned out eventually. And thanks for the good test coverage, it's a shame we can't assert facts about the generated code here...

Can you create a pull request from your `sema-autotag` branch?
