### ISSUE TITLE
Extra string types not recognised

### ISSUE THREAD

**Issue by viraptor** [kimgr/asn1ate#27]
Some string types are recognised by parser, but not output properly. TeletexString and UniversalString are not prefixed with `char.`

**Comment by kimgr** [comment]
There's a mapping in `pyasn1gen.py` -- `_ASN1_BUILTIN_TYPES` where you can add this translation. A pull request (with additional tests, see `string_types.asn`) would be very welcome!

**Comment by kimgr** [comment]
Fixed in PR #28.
