### ISSUE TITLE
OBJECT IDENTIFIER Error 

### ISSUE THREAD

**Issue by Mourhamo** [kimgr/asn1ate#36]
Hi,

I have a issue in case of an OBJECT IDENTIFIER define with two args:
OBJECT IDENTIFIER (id-qt-cps | id-qt-unotice)

i think the character | is not handeled 

find the ANS1 line 92

Thanks for help :)
[PKIX1Implicit88.asn1.txt](https://github.com/kimgr/asn1ate/files/352278/PKIX1Implicit88.asn1.txt)

**Comment by kimgr** [comment]
I think this is another example of constraint syntax -- the pipe character is not related to OBJECT IDENTIFIER but helps represent a constrained OBJECT IDENTIFIER type:

    PolicyQualifierId ::= OBJECT IDENTIFIER ( 1 | 0 )

A `PolicyQualifierId` in this example, thus, can only hold the values `OBJECT IDENTIFIER { 1 }` or `OBJECT IDENTIFIER { 0 }`.

I've made several attempts at handling constraint syntax better, but I haven't found anything that works well yet.

**Comment by kimgr** [comment]
This is now implemented on master.
