### ISSUE TITLE
interdependent asn1 files to py files

### ISSUE THREAD

**Issue by sky4133** [kimgr/asn1ate#71]
pyasn1gen.py can only transform one asn1 file to python. So how can i transform several asn1 files which are interdependent to py files?

**Comment by kimgr** [comment]
The multi-module problem isn't really solved in asn1ate.

The only way I can think of to work around this is to cat the files together in dependency order, and run the result through pyasn1gen.py.

**Comment by vpiserchia** [comment]
hi, I'm working on this exact use case and cooked a patch here: https://github.com/kimgr/asn1ate/pull/72
